export const cards = [
  {
    id: "card-1",
    icon: "./img/card/icon-p.png",
    title: "Эстетичная коронка из диоксида циркония с нанесением керамики",
    text: "На переднюю группу зубов",
    price: 17000,
    img: "./img/card/1.png",
    name1: "",
    price1: "",
    name2: "",
    price2: "",
    name3: "",
    price3: "",
  },
  {
    id: "card-2",
    icon: "./img/card/icon-r.png",
    title: "Зуб на импланте “под ключ”",
    text: "Консультация с составлением плана бесплатно",
    price: 35000,
    img: "./img/card/5.png",
    name1: "",
    price1: "",
    name2: "",
    price2: "",
    name3: "",
    price3: "",
  },
  {
    id: "card-3",
    icon: "./img/card/icon-p.png",
    title: "Имплантация",
    text: "Включает: хирургический этап установки эмпланта",
    price: "",
    img: "./img/card/3.png",
    name1: "Implantuim -",
    price1: 15000,
    name2: "Dentium -",
    price2: 21000,
    name3: "Ankylos -",
    price3: 29000,
  },
  {
    id: "card-4",
    icon: "./img/card/icon-r.png",
    title: "Лечение кариеса одного зуба",
    text: "Включает: обезболивание, препарирование, медикаментозная обработка, пломбирование <br/> <br/> Условия: разрушение менее ½, лечение в одно посещение",
    price: 2500,
    img: "./img/card/4.png",
    name1: "",
    price1: "",
    name2: "",
    price2: "",
    name3: "",
    price3: "",
  },
  {
    id: "card-5",
    icon: "./img/card/icon-p.png",
    title: "Комплексная профилактическая чистка",
    text: "Включает: защита слизистой и кожи лица ретрактор «OptraGate», снятие минерализованных зубных отложений у/з стайлером «Piezon» со всех зубов, полировка песткоструйным аппаратом и полировочной пастой, глубокая минерализация эмали, консультация",
    price: 2000,
    img: "./img/card/2.png",
    name1: "",
    price1: "",
    name2: "",
    price2: "",
    name3: "",
    price3: "",
  },
  {
    id: "card-6",
    icon: "./img/card/icon-r.png",
    title: "Коронка из диоксида циркония",
    text: "Условия: в полную анотомию. Подходит на боковую группу зубов. ",
    price: 9000,
    img: "./img/card/6.png",
    name1: "",
    price1: "",
    name2: "",
    price2: "",
    name3: "",
    price3: "",
  },
];